general:
  log_level: DEBUG

playground:
  api_url: http://localhost:8000
  max_api_key_expiration_days: 365
  cache_ttl: 1800
  database_url: postgresql://postgres:changeme@${POSTGRES_HOST}:5432/playground

auth:
  master_username: master
  master_key: changeme

mcp:
  mcp_bridge_url: http://${MCP_BRIDGE_HOST}:${MCP_BRIDGE_PORT}

web_search:
  - type: brave
    model: albert-small
    args:
      api_key: ${BRAVE_API_KEY}

databases:
  - type: qdrant
    model: embeddings-small
    args:
      url: http://${QDRANT_HOST}:${QDRANT_PORT_HTTP}
      api_key: changeme
      prefer_grpc: True
      grpc_port: ${QDRANT_GRPC_PORT}
      timeout: 10

  - type: redis
    args:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: changeme

  - type: sql # API database (async)
    context: api
    args:
      url: postgresql+asyncpg://postgres:changeme@${POSTGRES_HOST}:${POSTGRES_PORT}/api
      echo: False
      pool_size: 5
      max_overflow: 10
      pool_pre_ping: True
      connect_args:
        server_settings:
          statement_timeout: "120s"

  - type: sql # Playground database (sync)
    context: playground
    args:
      url: postgresql://postgres:changeme@${POSTGRES_HOST}:${POSTGRES_PORT}/playground
      echo: False
      pool_size: 5
      max_overflow: 10
      pool_pre_ping: True


models:
  - id: albert-large
    type: text-generation
    owned_by: test
    aliases: ["mistralai/Mistral-Small-3.1-24B-Instruct-2503"]
    clients:
      - model: mistralai/Mistral-Small-3.1-24B-Instruct-2503
        type: albert
        args:
          api_url: https://albert.api.staging.etalab.gouv.fr
          api_key: ${ALBERT_API_KEY}
          timeout: 120

  - id: albert-small
    type: text-generation
    aliases: ["meta-llama/Llama-3.1-8B-Instruct"]
    clients:
      - model: albert-small
        type: albert
        args:
          api_url: https://albert.api.etalab.gouv.fr
          api_key: ${ALBERT_API_KEY}
          timeout: 120

  - id: embeddings-small
    type: text-embeddings-inference
    aliases: ["BAAI/bge-m3"]
    clients:
      - model: BAAI/bge-m3
        type: albert
        args:
          api_url: https://albert.api.etalab.gouv.fr
          api_key: ${ALBERT_API_KEY}
          timeout: 120

  - id: audio-large
    type: automatic-speech-recognition
    aliases: ["openai/whisper-large-v3"]
    clients: 
      - model: audio-large
        type: albert
        args:
          api_url: https://albert.api.etalab.gouv.fr
          api_key: ${ALBERT_API_KEY}
          timeout: 120

  - id: rerank-small
    type: text-classification
    aliases: ["BAAI/bge-reranker-v2-m3"]
    clients:
      - model: rerank-small
        type: albert
        args:
          api_url: https://albert.api.etalab.gouv.fr
          api_key: ${ALBERT_API_KEY}
          timeout: 120
         

