general:
  log_level: DEBUG
  # disabled_routers:
  #   - ocr


playground:
  api_url: http://${API_HOST}:8000
  max_api_key_expiration_days: 365
  cache_ttl: 1800
  database_url: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/playground

auth:
  master_username: master
  master_key: changeme

monitoring:
  postgres:
    enabled: true

mcp:
  mcp_bridge_url: http://${MCP_BRIDGE_HOST}:${MCP_BRIDGE_PORT}

web_search:
  - type: brave
    model: albert-small
    args:
      api_key: ${BRAVE_API_KEY}

databases:
  - type: elasticsearch
    context: api
    model: my-embeddings-model
    args:
      hosts: http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
      basic_auth:
        - ${ELASTICSEARCH_USERNAME}
        - ${ELASTICSEARCH_PASSWORD}

  - type: redis
    context: api
    args:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: changeme

  - type: sql # API database (async)
    context: api
    args:
      url: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/api
      echo: False
      pool_size: 5
      max_overflow: 10
      pool_pre_ping: True
      connect_args:
        server_settings:
          statement_timeout: "120s"

  - type: sql # Playground database (sync)
    context: playground
    args:
      url: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/playground
      echo: False
      pool_size: 5
      max_overflow: 10
      pool_pre_ping: True

models:
  - id: albert-large
    type: text-generation
    owned_by: test
    aliases: ["mistralai/Mistral-Small-3.1-24B-Instruct-2503"]
    clients:
      - model: mistralai/Mistral-Small-3.1-24B-Instruct-2503
        type: albert
        args:
          api_url: ${ALBERT_API_URL}
          api_key: ${ALBERT_API_KEY}
          timeout: 120

  - id: albert-small
    type: text-generation
    aliases: ["meta-llama/Llama-3.1-8B-Instruct"]
    clients:
      - model: albert-small
        type: albert
        args:
          api_url: ${ALBERT_API_URL}
          api_key: ${ALBERT_API_KEY}
          timeout: 120

  - id: embeddings-small
    type: text-embeddings-inference
    aliases: ["BAAI/bge-m3"]
    clients:
      - model: BAAI/bge-m3
        type: albert
        args:
          api_url: ${ALBERT_API_URL}
          api_key: ${ALBERT_API_KEY}
          timeout: 120

  - id: audio-large
    type: automatic-speech-recognition
    aliases: ["openai/whisper-large-v3"]
    clients:
      - model: audio-large
        type: albert
        args:
          api_url: ${ALBERT_API_URL}
          api_key: ${ALBERT_API_KEY}
          timeout: 120

  - id: rerank-small
    type: text-classification
    aliases: ["BAAI/bge-reranker-v2-m3"]
    clients:
      - model: rerank-small
        type: albert
        args:
          api_url: ${ALBERT_API_URL}
          api_key: ${ALBERT_API_KEY}
          timeout: 120

  - id: my-language-model
    type: text-generation
    clients:
      - model: gpt-3.5-turbo
        type: openai
        params:
          total: 70
          active: 70
          zone: WOR
        args:
          api_url: https://api.openai.com
          api_key: ${OPENAI_API_KEY}
          timeout: 60

  - id: my-embeddings-model
    type: text-embeddings-inference
    clients:
      - model: text-embedding-3-small
        type: openai
        args:
          api_url: https://api.openai.com
          api_key: ${OPENAI_API_KEY}
          timeout: 60
