"""create modelrouter modelalias modelclient tables

Revision ID: bda6e849a5d9
Revises: 37d92be0a44c
Create Date: 2025-07-12 16:24:40.300932

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bda6e849a5d9"
down_revision: Union[str, None] = "37d92be0a44c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "modelrouter",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("routing_strategy", sa.String(), nullable=False),
        sa.Column("from_config", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_modelrouter_id"), "modelrouter", ["id"], unique=False)
    op.create_table(
        "modelclient",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("model_router_id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("prompt_token_cost", sa.Integer(), nullable=True),
        sa.Column("completion_token_cost", sa.Integer(), nullable=True),
        sa.Column("total_parameters", sa.Integer(), nullable=True),
        sa.Column("active_parameters", sa.Integer(), nullable=True),
        sa.Column("model_zone", sa.String(), nullable=True),
        sa.Column("api_url", sa.String(), nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column("timeout", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["model_router_id"], ["modelrouter.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_modelclient_id"), "modelclient", ["id"], unique=False)
    op.create_table(
        "modelrouteralias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alias", sa.String(), nullable=False),
        sa.Column("model_router_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["model_router_id"], ["modelrouter.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_modelrouteralias_id"), "modelrouteralias", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_modelrouteralias_id"), table_name="modelrouteralias")
    op.drop_table("modelrouteralias")
    op.drop_index(op.f("ix_modelclient_id"), table_name="modelclient")
    op.drop_table("modelclient")
    op.drop_index(op.f("ix_modelrouter_id"), table_name="modelrouter")
    op.drop_table("modelrouter")
    # ### end Alembic commands ###
